### ISSUE TITLE
Insert mode snippet list

### ISSUE THREAD

**Issue by randrej** [neoclide/coc-snippets#75]
I know you can issue a command in normal mode which presents you with a list of snippets you can fuzzily search: `:CocList snippets`.

But, you cannot insert a snippet when you find it in that list. While I was using Ultisnips proper, I used to map `fzf.vim`'s `:Snippets` in the following way: 

```vim
inoremap <C-U>  <C-O>:Snippets<CR>
```
This way I could pick and insert a snippet in insert mode, by pressing enter after picking the snippet (I believe I still had to expand it).

Is it possible to do something similar with coc-snippets? None of the available actions of `:CocList snippets` inserts the snippet name.

**Comment by chemzqm** [comment]
No such kind of support since `<C-o>` could be buggy with coc list, checkout `:h coc#start()` for completion with specific source.

**Comment by bratekarate** [comment]
Can you explain how `coc#start()` can be used for this scenario? Are you sure it is possible to open a list with completion for all snippets?

I tried to map it as follows: `inoremap <C-w> <C-R>=coc#start({'source': 'snippets'})<CR>`

It does only work if I press `<C-w>` after I started typing a word. When I hit `<C-space>` (`coc#refresh` binding), the list opens. But if I press `<C-w>` subsequently, the list closes. Please help me, because I don't know how to configure it. It *must* be possible to configure somehow.

**Comment by chemzqm** [comment]
@bratekarate that keymappings should just work, use `:verbose imap <C-w>` to make sure it's working, and maybe there's no matched snippets.

**Comment by bratekarate** [comment]
@chemzqm 
Thanks for your fast reply. I'm sorry if I did not make clear what I meant. 

> that keymappings should just work, use :verbose imap <C-w> to make sure it's working

The keymapping works, I verified it. But that's not the point. It does not work the way I expect. The issue is that I want the *full, unfiltered* list. 

>  and maybe there's no matched snippets.

That's impossible. If I type `for` and hit `<C-w>` in a python file, it shows me the snippets that include `for` (which is a step in the right direction). So if I type nothing, there must be matches too. I want them *all*, unfiltered, in one list. Not only for a typed word.  

Just like the OP, but not with `CocList`, I'm trying it with your suggestion, `coc#start()`. Maybe you did not mean it is possible and I misunderstood?

Test cases with expected results:
    1. go to insert mode, press `<C-w>` --> see *all* my snippets for the filetype
    2. go to insert mode, press `<C-space>`, then `<C-w>` --> see *all* my snippets for the filetype

Actual results:
    1. Nothing happens.
    2. Completion overlay opens with keyword suggestions first, but then immediately closes after hitting `<C-w>`

Option 1 would be optimal, but I don't mind option 2.

I just need to know if it is possible to use `coc#start()` for snippets without any text filter or not.

**Comment by chemzqm** [comment]
No, the completion only shows snippets that matched at current position, use `:CocList snippets` for all snippets of current buffer.

**Comment by bratekarate** [comment]
Ok , that probalby clarifies it. I was just surprised because this thread asked about inserting from the entire list.

Just to be really sure, there is absolutely no way to somehow get a completion overlay with all my snippets for the filetype? The only way is to use completion while typing and use `CocList snippets` only as an overview/edit menu?

I would be happy to try an hack together something for myself, if I had any clue which direction to look first. Because this really makes a speed difference to me.

**Comment by chemzqm** [comment]
It's feature to no show unusable snippets.

**Comment by bratekarate** [comment]
Well, I don't think I agree with you about it being a feature, but nevermind....I will look into it and see if I can customize it for my own needs. Probably what I do doesn't make much sense, but I want to see what's possible and maybe something interesting comes out of it.
